apiVersion: v1
kind: ConfigMap
metadata:
  name: sdp-ca-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdp-k8s-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
data:
  sdp-ca.conf: |-
    [ req ]
    default_bits       = 2048
    default_md         = sha512
    default_keyfile    = ca.key
    prompt             = no
    encrypt_key        = yes
    distinguished_name = req_distinguished_name
    req_extensions     = v3_req

    [ req_distinguished_name ]
    countryName            = "SE"
    stateOrProvinceName    = "Goteborg"
    localityName           = "Goteborg"
    postalCode             = ""
    streetAddress          = "Majorna"
    organizationName       = "appgate"
    organizationalUnitName = "devops"
    commonName             = "devops.appgate.com"
    emailAddress           = "no-reply@appgate.com"

    [ v3_req ]
    subjectAltName  = DNS:appgate.com

    [ ext ]
    basicConstraints=CA:TRUE,pathlen:0
