apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-k8s-client.fullname" . }}
  labels:
  {{- include "sdp-k8s-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sdp-k8s-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sdp-k8s-client.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "sdp-k8s-client.serviceAccountName" .}}
      volumes:
        - name: sdp-injector-secrets-and-config
          projected:
            sources:
              - secret:
                  name: {{ include "sdp-k8s-client.injector-secret" . }}
                  items:
                    - key: sdp-injector-crt.pem
                      path: sdp-injector-crt.pem
                    - key: sdp-injector-key.pem
                      path: sdp-injector-key.pem
              - configMap:
                  name: {{ include "sdp-k8s-client.sidecar-config" . }}
                  items:
                    - key: sdp-sidecars.json
                      path: sdp-sidecars.json
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: RUST_LOG
              value: {{ .Values.sdp.injector.image.logLevel | default "info" }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.sdp.injector.image.repository }}
          imagePullPolicy: {{ .Values.sdp.injector.image.pullPolicy }}
          volumeMounts:
            - name: sdp-injector-secrets-and-config
              mountPath: /opt/sdp-injector/k8s
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
