apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sdp-k8s-client.fullname" . }}-postdelete
  labels:
  {{- include "sdp-k8s-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: {{ include "sdp-k8s-client.serviceAccountName" . }}
      restartPolicy: Never
      volumes:
        - name: ca-config
          configMap:
            name: sdp-ca-config-{{ .Release.Name }}
        - name: sdp-injector-config
          configMap:
            name: sdp-injector-config-{{ .Release.Name }}
        - name: sdp-admission-webhook
          configMap:
            name: sdp-admission-webhook-{{ .Release.Name }}
        - name: tmp
          emptyDir: {}
      securityContext:
        runAsUser: 1000
      containers:
        - name: delete-secret
          image: "bitnami/kubectl"
          command: ["kubectl"]
          args: [ "delete", "secret", "{{ include "sdp-k8s-client.injector-secret" . }}", "--namespace", "{{ .Release.Namespace }}"]
        - name: delete-admission-webhook
          image: "bitnami/kubectl"
          command: ["kubectl"]
          args: [ "delete", "mutatingwebhookconfigurations", "sdp-admission-webhook-{{ .Release.Name }}"]