{{ if .Values.rbac.create}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sdp-k8s-client.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdp-k8s-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sdp-k8s-client.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdp-k8s-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
subjects:
  - kind: ServiceAccount
    name: {{ include "sdp-k8s-client.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sdp-k8s-client.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
