apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp-k8s-client.fullname" . }}
  labels:
    {{- include "sdp-k8s-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      name: https-webhooks
  selector:
    {{- include "sdp-k8s-client.selectorLabels" . | nindent 4 }}
