apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: internal-server
  name: internal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-server
  template:
    metadata:
      labels:
        app: internal-server
      annotations:
        sdp-injector: "false"
    spec:
      containers:
      - image: python:3.9-slim
        name: server
        command: ["python3"]
        args: ["-m", "http.server",  "--directory", "/tmp/"]
---
apiVersion: v1
kind: Service
metadata:
  name: internal-server
spec:
  selector:
    app: internal-server
  ports:
    - port: 80
      targetPort: 8000
