# Default values for sdp-k8s-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

sdp:
  injector:
    image:
      repository: ghcr.io/appgate/sdp-k8s-client/sdp-injector
      tag: latest
      logLevel: info

  headlessService:
    image:
      repository: ghcr.io/appgate/sdp-k9s-client/sdp-headless-service
      tag: latest
      pullPolicy: Always

  headlessDriver:
    image:
      repository: ghcr.io/appgate/sdp-k8s-client/sdp-headless-driver
      tag: bf29001f31e85fe20b78ecb7ff34ecd4c67c4bbd
      pullPolicy: Always

  dnsmasq:
    image:
      repository: ghcr.io/appgate/sdp-k8s-client/sdp-dnsmasq
      tag: latest
      pullPolicy: Always

serviceAccount:
  create: true

rbac:
  create: true

service:
  type: ClusterIP
  port: 443
