name: SDP k8s client

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  sdp-injector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t sdp-injector -f docker/sdp-injector-Dockerfile .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/sdp-injector-Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-injector:latest
            ghcr.io/${{ github.repository }}/sdp-injector:${{ github.sha }}

  sdp-dnsmasq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t sdp-dnsmasq -f docker/sdp-dnsmasq-Dockerfile .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/sdp-dnsmasq-Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-dnsmasq:latest
            ghcr.io/${{ github.repository }}/sdp-dnsmasq:${{ github.sha }}
