name: SDP k8s client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sdp-injector:
    runs-on: ubuntu-latest
    steps:
      - name: Get build profile
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              echo '::set-output name=PROFILE::release'
          else
              echo '::set-output name=PROFILE::debug'
          fi
        id: build-profile
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PROFILE=${{ steps.build-profile.outputs.PROFILE }}
          context: .
          file: docker/sdp-injector-Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/appgate/sdp-injector:latest
            ghcr.io/appgate/sdp-injector:${{ github.sha }}

  sdp-dnsmasq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/sdp-dnsmasq-Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/appgate/sdp-dnsmasq:latest
            ghcr.io/appgate/sdp-dnsmasq:${{ github.sha }}
