name: Appgate SDP Kubernetes Client

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build rust code
        run: docker build -t sdp-injector --target sdp-builder -f docker/sdp-injector-Dockerfile .
